spring:
  application:
    name: order-management
  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate  
